---
abstract: 'Organise your Moose types in libraries'
author:
  - "Robert \"phaylon\" Sedlacek <rs@474.at>"
build_requires:
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::Moose: 0
  Test::More: 0.80
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.88'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Carp::Clan: 6.00
  Moose: 0.61
  Scalar::Util: 1.19
  Sub::Install: 0.924
  Sub::Name: 0
  namespace::clean: 0.08
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.15
