--- 
abstract: Organise your Moose types in libraries
author: Robert 'phaylon' Sedlacek <rs@474.at>
build_requires: 
  FindBin: 0
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Types
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Moose: 0.24
  Sub::Install: 0.922
  Sub::Uplevel: 0.14
  namespace::clean: 0.04
version: 0.02
