use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
SUBTYPES
coercions
subtypes
subtyping
instantiation
TODO
Organise
parameterized
parameterize
subtype
Robert
phaylon
Sedlacek
rs
Dave
Rolsky
autarch
Karen
Etheridge
ether
John
Napiorkowski
jjnapiork
Rafael
Kitover
rkitover
Florian
Ragwitz
rafl
Matt
Trout
mst
Hans
Dieter
Pearcey
hdp
Jesse
Luehrs
doy
Tomas
Doran
t0m
bobtfish
matthewt
Justin
Hunter
justin
Kent
Fredric
kentfredric
Paul
Fenwick
pjf
Graham
Knop
haarg
lib
MooseX
Types
UndefinedType
Moose
CheckedUtilExports
Util
Base
Wrapper
Combine
TypeDecorator
