use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006002
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
SUBTYPES
coercions
subtypes
subtyping
instantiation
TODO
Organise
parameterized
parameterize
subtype
Robert
phaylon
Sedlacek
rs
Dave
Rolsky
autarch
Florian
Ragwitz
rafl
Graham
Knop
haarg
Hans
Dieter
Pearcey
hdp
Jesse
Luehrs
doy
John
Napiorkowski
jjnapiork
Justin
Hunter
justin
Karen
Etheridge
ether
Kent
Fredric
kentfredric
Matt
Trout
mst
Paul
Fenwick
pjf
Rafael
Kitover
rkitover
Tomas
Doran
t0m
bobtfish
matthewt
lib
MooseX
Types
Util
Moose
Combine
Wrapper
UndefinedType
CheckedUtilExports
Base
TypeDecorator
